services:
  nextjs:
    build:
      context: .
      args:
        DOMAIN_URL: ${DOMAIN_URL}
        PUBLIC_API_BASE: ${PUBLIC_API_BASE}
    ports:
      - "3001:3000"
    environment:
      DOMAIN_URL: ${DOMAIN_URL}
      PUBLIC_API_BASE: ${PUBLIC_API_BASE}
      NODE_ENV: production
    restart: unless-stopped