services:
  nextjs:
    build: .
    ports:
      - "3000:3000"
    environment:
      DOMAIN_URL: https://YourInstance.xpr.cloud
      PUBLIC_API_BASE: ""
      NODE_ENV: production
    restart: unless-stopped